version: "3"
services:
  postgres:
    image: postgres
    network_mode: host
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database_agent
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external: false
