name: Pull Request Review
on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup python and poetry
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install Poetry
        run: pip install poetry

      - name: Setup databases
        run: docker-compose up -d

      - name: Waiting health check
        run: sleep 10

      - name: Poetry install
        run: poetry install --no-interaction --no-root

      - name: Build
        run: poetry build

      - name: Tests
        run: poetry run pytest